language: node_js
node_js:
- '12'
services:
- postgresql
before_script:
- npm run lint
script:
- npm run test:ci
env:
  global:
  - DB_USER=postgres
  - DB_NAME=auth_test_db
  - DB_PORT=5432
  - DB_PASSWORD=''
  - DB_HOST=localhost
deploy:
  provider: heroku
  api_key:
    secure: bWmjtf0lVpHwjd3L+9VN2zTAwg04yE3ujVvEtVhDbUa86wIA0xheshYXrDVVCJq6UusJgouPax0jywlfSlLbTsJaPVtQla4OIAqvnRIsNdJL1zh6WZWuDi6ykIcLI2P1s07W3m39Ox8FoOZvbzX97iKROarvUFgXfST2491FJUyIFt3jKtI4ONkgusZnLVEAtpjjv2Hq2jR4kwYxuG7FxkuyrwZ5RjzkHFQObRkl53Z1ffBl2bFrnLiQU0b+gwYA5tnHTPjz/+hAJ/VGW2frLAj5NKPwtbrGFpw5Bt/JzVS77psCQxI+e1lfS8IGDRArsy6wK/tvxERxY90c45ZDnZKIxPpi93hOWXIouiCiFlJQNYX7BwZ/DXnmNxq6Lm4hAoC53gm7pn8UfdlGYwueIl9ftXhhAsMWCzzaS+iMIHifttlGcS5gYYqhnZyHo0SZ9JlcGUjnP1uj5DFi7klMUP+DMoLt2siDOfW0ZYE+QDfhI/Qj7UMrCMzu3pXjpDmTb1JMiMdqZFGactxKWm9Q6zTZ7KEmywlCyfPxlBO0B9oiNBVmg/rql3Cee1BPPZpRdDxnAqPCsoMRfSzDAh3dfCYxcCl/sH4VpCr/nv8piZnweh//ZjuyuNqo+LNMShgH8KqOqoLWYJXXrOXcKWrlo38PAB3w0PGuOCpemR5+Z74=
  app: fury-auth-microservice
  on:
    branch: develop
