version: "3"
services:
  app:
    container_name: microapi_app
    restart: always
    build: .
    ports:
      - "8889:8000"
      - "8887:8888"
      - "8886:5000"
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27018:27017"
